# Generated by Django 3.0.4 on 2020-04-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200326_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('door count', 'DOOR'), ('scanner', 'SCANNER')], default='door count', max_length=10),
        ),
    ]
