# Generated by Django 3.0.4 on 2020-04-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('DOOR', 'DOOR'), ('SCANNER', 'SCANNER')], default='door count', max_length=10),
        ),
    ]
