# Generated by Django 3.0.4 on 2020-04-02 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200402_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorCountInstance',
            fields=[
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.Task')),
                ('id', models.IntegerField()),
                ('sensor_id', models.CharField(max_length=100)),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('in_count', models.IntegerField()),
                ('out_count', models.IntegerField()),
                ('sensor_type', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=100)),
                ('device_type', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=255)),
                ('sensor_group', models.CharField(max_length=255)),
                ('tmestamp', models.FloatField()),
            ],
        ),
    ]
