# Generated by Django 3.0.4 on 2020-04-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_doorcountinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doorcountinstance',
            name='end_time',
            field=models.DecimalField(decimal_places=20, max_digits=100),
        ),
        migrations.AlterField(
            model_name='doorcountinstance',
            name='start_time',
            field=models.DecimalField(decimal_places=20, max_digits=100),
        ),
        migrations.AlterField(
            model_name='doorcountinstance',
            name='tmestamp',
            field=models.DecimalField(decimal_places=20, max_digits=100),
        ),
    ]
