# Generated by Django 3.0.4 on 2020-04-02 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200402_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doorcountinstance',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.Task'),
        ),
    ]
